// Code generated by protoc-gen-go.
// source: gochat.proto
// DO NOT EDIT!

/*
Package gochat is a generated protocol buffer package.

It is generated from these files:
	gochat.proto

It has these top-level messages:
	ChatMessage
*/
package gochat

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ChatMessage struct {
	Name    string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message" json:"message,omitempty"`
}

func (m *ChatMessage) Reset()                    { *m = ChatMessage{} }
func (m *ChatMessage) String() string            { return proto.CompactTextString(m) }
func (*ChatMessage) ProtoMessage()               {}
func (*ChatMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *ChatMessage) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ChatMessage) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*ChatMessage)(nil), "gochat.ChatMessage")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for GroupChat service

type GroupChatClient interface {
	Chat(ctx context.Context, opts ...grpc.CallOption) (GroupChat_ChatClient, error)
}

type groupChatClient struct {
	cc *grpc.ClientConn
}

func NewGroupChatClient(cc *grpc.ClientConn) GroupChatClient {
	return &groupChatClient{cc}
}

func (c *groupChatClient) Chat(ctx context.Context, opts ...grpc.CallOption) (GroupChat_ChatClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_GroupChat_serviceDesc.Streams[0], c.cc, "/gochat.GroupChat/Chat", opts...)
	if err != nil {
		return nil, err
	}
	x := &groupChatChatClient{stream}
	return x, nil
}

type GroupChat_ChatClient interface {
	Send(*ChatMessage) error
	Recv() (*ChatMessage, error)
	grpc.ClientStream
}

type groupChatChatClient struct {
	grpc.ClientStream
}

func (x *groupChatChatClient) Send(m *ChatMessage) error {
	return x.ClientStream.SendMsg(m)
}

func (x *groupChatChatClient) Recv() (*ChatMessage, error) {
	m := new(ChatMessage)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for GroupChat service

type GroupChatServer interface {
	Chat(GroupChat_ChatServer) error
}

func RegisterGroupChatServer(s *grpc.Server, srv GroupChatServer) {
	s.RegisterService(&_GroupChat_serviceDesc, srv)
}

func _GroupChat_Chat_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(GroupChatServer).Chat(&groupChatChatServer{stream})
}

type GroupChat_ChatServer interface {
	Send(*ChatMessage) error
	Recv() (*ChatMessage, error)
	grpc.ServerStream
}

type groupChatChatServer struct {
	grpc.ServerStream
}

func (x *groupChatChatServer) Send(m *ChatMessage) error {
	return x.ServerStream.SendMsg(m)
}

func (x *groupChatChatServer) Recv() (*ChatMessage, error) {
	m := new(ChatMessage)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _GroupChat_serviceDesc = grpc.ServiceDesc{
	ServiceName: "gochat.GroupChat",
	HandlerType: (*GroupChatServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Chat",
			Handler:       _GroupChat_Chat_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "gochat.proto",
}

func init() { proto.RegisterFile("gochat.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 124 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x49, 0xcf, 0x4f, 0xce,
	0x48, 0x2c, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x83, 0xf0, 0x94, 0xac, 0xb9, 0xb8,
	0x9d, 0x33, 0x12, 0x4b, 0x7c, 0x53, 0x8b, 0x8b, 0x13, 0xd3, 0x53, 0x85, 0x84, 0xb8, 0x58, 0xf2,
	0x12, 0x73, 0x53, 0x25, 0x18, 0x15, 0x18, 0x35, 0x38, 0x83, 0xc0, 0x6c, 0x21, 0x09, 0x2e, 0xf6,
	0x5c, 0x88, 0xb4, 0x04, 0x13, 0x58, 0x18, 0xc6, 0x35, 0x72, 0xe6, 0xe2, 0x74, 0x2f, 0xca, 0x2f,
	0x2d, 0x00, 0x99, 0x20, 0x64, 0xc6, 0xc5, 0x02, 0xa6, 0x85, 0xf5, 0xa0, 0x16, 0x21, 0x99, 0x2b,
	0x85, 0x4d, 0x50, 0x89, 0x41, 0x83, 0xd1, 0x80, 0x31, 0x89, 0x0d, 0xec, 0x20, 0x63, 0x40, 0x00,
	0x00, 0x00, 0xff, 0xff, 0x9a, 0xaf, 0xd8, 0xdc, 0xa0, 0x00, 0x00, 0x00,
}
